name: pullreq

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: voxmedia/github-action-slack-notify-build@v1
        id: slack
        with:
          channel: notif-oss
          status: 初期化中
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: npm config rm proxy
      - run: npm config rm https-proxy
      - run: npm config set fetch-retry-mintimeout 20000
      - run: npm config set fetch-retry-maxtimeout 120000
      - run: npm config set registry https://registry.npmjs.org/

      - run: npm install --no-save yarn

      - uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: notif-oss
          status: yarn install
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - run: npx yarn install --frozen-lockfile

      - uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: notif-oss
          status: テスト中
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - run: npx yarn test

      - uses: voxmedia/github-action-slack-notify-build@v1
        if: success()
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: notif-oss
          status: テストOK
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - uses: voxmedia/github-action-slack-notify-build@v1
        if: failure()
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: notif-oss
          status: エラー発生
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
